In [1]:
#Exploratory Data Analysis of "NyC Dogs Dataset"

##Importing required libraries.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Dogs.csv", low_memory=False)

In [3]:
df.head()

,AnimalName,AnimalGender,AnimalBirthYear,BreedName,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year
0,PAIGE,F,2014,American Pit Bull Mix / Pit Bull Mix,10035.0,09/12/2014,09/12/2017,2016
1,YOGI,M,2010,Boxer,10465.0,09/12/2014,10/02/2017,2016
2,ALI,M,2014,Basenji,10013.0,09/12/2014,09/12/2019,2016
3,QUEEN,F,2013,Akita Crossbreed,10013.0,09/12/2014,09/12/2017,2016
4,LOLA,F,2009,Maltese,10028.0,09/12/2014,10/09/2017,2016

In [4]:
df.tail()

,AnimalName,AnimalGender,AnimalBirthYear,BreedName,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year
819318,PEPPER,F,2024,"Dachshund, Long Haired Miniature",11365.0,12/31/2024,12/31/2025,2024
819319,WHISKEY,M,2021,Pembroke Welsh Corgi,10036.0,12/31/2024,12/31/2025,2024
819320,HAYDEN,F,2022,Shih Tzu,10009.0,12/31/2024,12/31/2025,2024
819321,YODA,M,2019,Italian Greyhound,11360.0,12/31/2024,12/31/2029,2024
819322,CHLOE,F,2017,Cavalier King Charles Spaniel Crossbreed,11226.0,12/31/2024,01/07/2026,2024

In [5]:
df.dtypes

AnimalName             object
AnimalGender           object
AnimalBirthYear        object
BreedName              object
ZipCode               float64
LicenseIssuedDate      object
LicenseExpiredDate     object
Extract Year            int64
dtype: object

In [8]:
df.shape

(819323, 8)